### ISSUE TITLE
Component test not exiting

### ISSUE THREAD

**Issue by EROIN** [numaproj/numaflow-java#174]
calling 
`client.close();` and `sourceTransformerTestKit.stopServer();` does not exit the test. However, `lsof` command shows no process running on port 50051.

**Comment by EROIN** [comment]
When run locally with nuemaflow v1.1.3, it gives the error: `java.lang.NoClassDefFoundError: scala/$less$colon$less`.
Downgrading to v1.1.1 fixes the issues.

Moreover, after removing the below dependencies from pom.xml, it works with v1.1.3 as well.
```
<dependency>
    <groupId>org.sonarsource.java</groupId>
    <artifactId>sonar-jacoco-listeners</artifactId>
    <version>3.8</version>
    <scope>test</scope>
</dependency>

<dependency>
    <groupId>com.intuit.ctg.tools</groupId>
    <artifactId>perf-utils</artifactId>
    <version>1.0.3</version>
    <scope>test</scope>
</dependency>
```

**Comment by yhl25** [comment]
closed in https://github.com/numaproj/numaflow-java/pull/176
